name: FastAPI run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-run:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Use Python versions compatible with Apple M1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}  # Use the specified Python version

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Start Backend Server
        run: uvicorn main:app --reload &
